version: '3'

volumes:
  database: {}

services:
  database:
    image: postgres:11.6
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: edgar
      PGUSER: docker
      PGPASSWORD: docker
    ports:
      - '5432:5432'
    volumes:
      - 'database:/var/lib/postgresql/data'

  api:
    image: node:14.3
    working_dir: '/var/www'
    depends_on:
      - database
    volumes:
      - './server:/var/www:cached'
    ports:
      - 8080:3000
    command: npm run start:dev

  client:
    image: node:14.3
    working_dir: '/var/www'
    depends_on:
      - api
    volumes:
      - './client:/var/www:cached'
    ports:
      - 8000:3000
      - 10000:10000
    command: npm run dev
