version: '3'

volumes:
  database: {}
  uploads: {}

services:
  database:
    image: postgres:11.6
    environment:
      POSTGRES_USER: permacoop
      POSTGRES_PASSWORD: permacoop
      POSTGRES_DB: permacoop
      PGUSER: permacoop
      PGPASSWORD: permacoop
    ports:
      - '5432:5432'
    volumes:
      - 'database:/var/lib/postgresql/data'

  api:
    image: node:14.2
    working_dir: '/var/www'
    depends_on:
      - database
    volumes:
      - './server:/var/www:cached'
      - 'uploads:/var/www/uploads'
    ports:
      - 8080:3000
    command: npm run start:dev

  client:
    image: node:14.2
    working_dir: '/var/www'
    depends_on:
      - api
    volumes:
      - './client:/var/www:cached'
    ports:
      - 8000:3000
    command: npm run dev
