version: '3'

volumes:
  database: {}

services:
  database:
    image: postgres:11.6
    environment:
      POSTGRES_USER: edgar
      POSTGRES_PASSWORD: edgar
      POSTGRES_DB: edgar
      PGUSER: edgar
      PGPASSWORD: edgar
    ports:
      - '5433:5432'
    volumes:
      - 'database:/var/lib/postgresql/data'

  api:
    image: node:14.2
    working_dir: '/var/www'
    depends_on:
      - database
    volumes:
      - './server:/var/www:cached'
    ports:
      - 8080:3000
    command: npm run start:dev

  client:
    image: node:14.2
    working_dir: '/var/www'
    depends_on:
      - api
    volumes:
      - './client:/var/www:cached'
    ports:
      - 8000:3000
    command: npm run dev
